## Day 8 of machine learning

# **Logistic Regression**

### Logistics regression is checked when the problem of classification comes up. In regression we basically predict the numeric value. Logistics regression is one which is used to predict the classification data. We classify it after reading the data into binary classes(True and False) and the other is multi class classifiaction(not in binary, more than one ) 

### There is another type of classifiaction which is called multi-label classifiaction in which we label the data with different label.

## In the classification of logistics regression. The following metrics are used which are quite important.
### 1- Accuracy score 
### 2- Recall score 
### 3- Precision score
### 4- F1 score 
### 5- Confusion metrics 


### Logistic Regression: It predicts which means proability the occurrence of an event. If it is 0 means does not occur and if 1 it means it highly occurs.It is proably equals to 0.5.

### Sgmoid Function is used in the logistics regression which works as a converstion of numeric value into binary value either in 0 or 1. 


### Assumption of logistic regression  
### 1- The dependent variable should be binary in nature.
### 2- The independent variables should be continuous in nature.
### 3- The relationship between the independent and dependent variable should be non-linear.
### 4- There should not be outliers in the data. Check the outliers

## **Coding Time**

In [4]:
# Import the libaries 

import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,recall_score, precision_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, MinMaxScaler

In [6]:
## Import the data 
df= sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

### Same as code of linear regression